// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHRPB-tWttIEQEa-BVx90Uqqlaw0FPYmg',
    appId: '1:39357918326:web:2ef4c2bf47239b0c3f0357',
    messagingSenderId: '39357918326',
    projectId: 'ordinazioni-ristorante-flutter',
    authDomain: 'ordinazioni-ristorante-flutter.firebaseapp.com',
    storageBucket: 'ordinazioni-ristorante-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd-HPuxQerLwJepWCTsOS50-qx5i62fUs',
    appId: '1:39357918326:android:f728c90cdaacbb8b3f0357',
    messagingSenderId: '39357918326',
    projectId: 'ordinazioni-ristorante-flutter',
    storageBucket: 'ordinazioni-ristorante-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUjLNJAf4DlM9V1uwGL2e5ZnZWz41GAv0',
    appId: '1:39357918326:ios:ec70bba2d3e50eff3f0357',
    messagingSenderId: '39357918326',
    projectId: 'ordinazioni-ristorante-flutter',
    storageBucket: 'ordinazioni-ristorante-flutter.appspot.com',
    iosBundleId: 'com.example.ordinazioniRistoranteFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUjLNJAf4DlM9V1uwGL2e5ZnZWz41GAv0',
    appId: '1:39357918326:ios:602cb843b7a703733f0357',
    messagingSenderId: '39357918326',
    projectId: 'ordinazioni-ristorante-flutter',
    storageBucket: 'ordinazioni-ristorante-flutter.appspot.com',
    iosBundleId: 'com.example.ordinazioniRistoranteFlutter.RunnerTests',
  );
}
